title: Pokemon Joel Version
description: Pokemon Joel is a rom based on Pokemon Emeraled using the <a href="https://github.com/pret/pokeemerald">pret.</a> (Insert URL)
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman